# services/report_generator.py
"""
PDF report generator using fpdf2.

Produces a clean, downloadable summary report with:
- Match scores
- Skill breakdown
- AI feedback sections
"""

from __future__ import annotations
import io
import logging
from datetime import datetime
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from services.analyzer import AnalysisResult

logger = logging.getLogger(__name__)


    
def generate_pdf_report(result: "AnalysisResult") -> bytes:
    """
    Generate a PDF report from an AnalysisResult and return as bytes.
    Returns empty bytes on failure.
    """
    try:
        from fpdf import FPDF

        pdf = FPDF()

        # ✅ ADD FONT HERE (AFTER pdf is created)
        pdf.add_font("DejaVu", "", "fonts\DejaVuSans.ttf", uni=True)
        pdf.add_font("DejaVu", "B", "fonts\DejaVuSans.ttf", uni=True)
        pdf.add_font("DejaVu", "I", "fonts\DejaVuSans.ttf", uni=True)

        pdf.set_auto_page_break(auto=True, margin=15)
        pdf.add_page()

        # ── Header ──────────────────────────────────────────────────────────
        pdf.set_font("DejaVu", "B", 22)
        pdf.set_text_color(15, 23, 42)
        pdf.cell(0, 12, "AI Resume Analysis Report", ln=True, align="C")

        pdf.set_font("DejaVu", "", 10)
        pdf.set_text_color(100, 100, 100)
        pdf.cell(0, 6, f"Generated on {datetime.now().strftime('%B %d, %Y at %H:%M')}", ln=True, align="C")
        pdf.ln(8)

        # ── Score Summary ────────────────────────────────────────────────────
        _section_header(pdf, "Match Score Summary")

        scores = [
            ("Combined Score", result.combined_score),
            ("TF-IDF Score", result.tfidf_score),
            ("BERT Score", result.bert_score if result.bert_available else None),
        ]
        for label, score in scores:
            if score is None:
                continue
            pdf.set_font("DejaVu", "B", 11)
            pdf.set_text_color(15, 23, 42)
            pdf.cell(80, 8, f"  {label}:", ln=False)
            pdf.set_font("DejaVu", "", 11)
            color = _score_color(score)
            pdf.set_text_color(*color)
            pdf.cell(0, 8, f"{score:.1f} / 100", ln=True)

        pdf.set_text_color(15, 23, 42)
        pdf.ln(4)

        # ── Skills ──────────────────────────────────────────────────────────
        skill_cat = result.skill_categorization
        present = skill_cat.get("present", [])
        missing = skill_cat.get("missing", [])

        _section_header(pdf, "Skill Analysis")

        pdf.set_font("DejaVu", "B", 11)
        pdf.set_text_color(0, 150, 80)
        pdf.cell(0, 7, f"  ✓ Matched Skills ({len(present)})", ln=True)
        pdf.set_font("DejaVu", "", 10)
        pdf.set_text_color(40, 40, 40)
        if present:
            pdf.multi_cell(0, 6, "  " + ", ".join(present))
        else:
            pdf.cell(0, 6, "  None detected.", ln=True)
        pdf.ln(3)

        pdf.set_font("DejaVu", "B", 11)
        pdf.set_text_color(200, 50, 50)
        pdf.cell(0, 7, f"  ✗ Missing Skills ({len(missing)})", ln=True)
        pdf.set_font("DejaVu", "", 10)
        pdf.set_text_color(40, 40, 40)
        if missing:
            pdf.multi_cell(0, 6, "  " + ", ".join(missing))
        else:
            pdf.cell(0, 6, "  None — great coverage!", ln=True)
        pdf.ln(4)

        # ── AI Feedback Sections ─────────────────────────────────────────────
        if result.feedback_sections:
            _section_header(pdf, "AI-Generated Feedback")
            section_labels = {
                "overall_assessment": "Overall Assessment",
                "strengths": "Strengths",
                "gaps": "Gaps & Weaknesses",
                "quick_wins": "Quick Wins",
                "long_term_recommendations": "Long-Term Recommendations",
                "keywords_to_add": "Keywords to Add",
                "interview_talking_points": "Interview Talking Points",
            }
            for key, label in section_labels.items():
                content = result.feedback_sections.get(key, "")
                if not content:
                    continue
                pdf.set_font("DejaVu", "B", 11)
                pdf.set_text_color(30, 30, 120)
                pdf.cell(0, 8, f"  {label}", ln=True)
                pdf.set_font("DejaVu", "", 10)
                pdf.set_text_color(40, 40, 40)
                pdf.multi_cell(0, 6, "  " + content.replace("•", "-"))
                pdf.ln(3)

        # ── Footer ──────────────────────────────────────────────────────────
        pdf.set_y(-15)
        pdf.set_font("DejaVu", "I", 8)
        pdf.set_text_color(150, 150, 150)
        pdf.cell(0, 10, "Generated by AI Resume Analyzer — for guidance only", align="C")

        return bytes(pdf.output())

    except Exception as exc:
        logger.error("PDF report generation failed: %s", exc)
        return b""


def _section_header(pdf, title: str):
    from fpdf import FPDF
    pdf.set_font("DejaVu", "B", 14)
    pdf.set_fill_color(230, 235, 255)
    pdf.set_text_color(15, 23, 100)
    pdf.cell(0, 9, f"  {title}", ln=True, fill=True)
    pdf.ln(3)
    pdf.set_text_color(15, 23, 42)


def _score_color(score: float) -> tuple:
    if score >= 80:
        return (0, 150, 80)
    elif score >= 65:
        return (200, 130, 0)
    elif score >= 45:
        return (200, 80, 0)
    else:
        return (180, 30, 30)
